drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar2(255),
    email varchar2(255),
    created_at date default now(),
    updated_at date default now(),
    primary key (id)
);

call next value for hibernate_sequence;
insert into member(id, name, email) values ( 1, 'martine' , 'martine@fastcampus.com' );

call next value for hibernate_sequence;
insert into member(id, name, email) values ( 2, 'dennis' , 'dennis@fastcampus.com' );

call next value for hibernate_sequence;
insert into member(id, name, email) values ( 3, 'sophia' , 'sophia@slowcampus.com' );

call next value for hibernate_sequence;
insert into member(id, name, email) values ( 4, 'james' , 'james@slowcampus.com' );

call next value for hibernate_sequence;
insert into member(id, name, email) values ( 5, 'martine' , 'martine@fastAnothercampus.com' );
