SELECT *
FROM EMPLOYEE;

SELECT ENO, ENAME, DNO
FROM EMPLOYEE;

SELECT DISTINCT DNO
FROM EMPLOYEE;

SELECT DISTINCT JOB, DNO
FROM EMPLOYEE;

SELECT ENAME, SALARY, SALARY*12+COMMISION, COMMISION
FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
RENAME COLUMN SALARY TO SAL;

ALTER TABLE EMPLOYEE
RENAME COLUMN COMMISION TO COMM;

SELECT ENAME, SAL, SAL*12+COMM AS ANNSAL, COMM
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
ORDER BY SAL;

ALTER TABLE EMPLOYEE
RENAME COLUMN MANAGER TO MGR;

SELECT *
FROM EMPLOYEE
ORDER BY SAL DESC;

SELECT *
FROM EMPLOYEE
ORDER BY DNO ASC, SAL DESC;

COMMIT;

SELECT *
FROM EMPLOYEE
WHERE ENO =7782;

SELECT *
FROM EMPLOYEE
WHERE DNO = 30
AND JOB = 'SALESMAN';

SELECT *
FROM EMPLOYEE
WHERE ENO=7499
AND DNO=30;

SELECT *
FROM EMPLOYEE
WHERE DNO=20
OR JOB='SALESMAN';

SELECT *
FROM EMPLOYEE
WHERE SAL*12=36000;

SELECT * 
FROM EMPLOYEE
WHERE SAL >=2500
AND JOB = 'ANALYST';

SELECT *
FROM EMPLOYEE
WHERE ENAME >= 'F';

SELECT *
FROM EMPLOYEE
WHERE ENAME <= 'FORZ';

SELECT *
FROM EMPLOYEE
WHERE JOB='MANAGER'
OR JOB='SALESMAN'
OR JOB ='CLERK';

SELECT *
FROM EMPLOYEE
WHERE JOB IN ('MANAGER', 'SALESMAN', 'CLERK');

SELECT *
FROM EMPLOYEE
WHERE JOB!='MANAGER'
AND JOB^='SALESMAN'
AND JOB<>'CLERK';

SELECT *
FROM EMPLOYEE
WHERE JOB NOT IN('MANAGER', 'SALESMAN', 'CLERK');

SELECT *
FROM EMPLOYEE
WHERE DNO IN (10, 20)
ORDER BY DNO;

SELECT *
FROM EMPLOYEE
WHERE SAL >= 2000
AND SAL <= 3000;

SELECT *
FROM EMPLOYEE
WHERE ENAME LIKE 'S%';

SELECT *
FROM EMPLOYEE
WHERE ENAME LIKE '_L%';

SELECT *
FROM EMPLOYEE
WHERE COMM IS NULL;

SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
WHERE DNO = 10
UNION
SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
WHERE DNO =20;

SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
MINUS
SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
WHERE DNO=10;

SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
INTERSECT
SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
WHERE DNO=10;

-- Q1 EMPLOYEE 테이블을 사용하여 다음과 같이 사원 이름(ENAME)이 S로 끝나는 사원 데이터를 모두 출력하시오
SELECT *
FROM EMPLOYEE
WHERE ENAME LIKE '%S';

-- Q2
SELECT ENO, ENAME, JOB, SAL, DNO
FROM EMPLOYEE
WHERE DNO=30
AND JOB='SALESMAN';

-- Q3
SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
WHERE DNO IN (20, 30)
AND SAL > 2000;

--Q3 집합사용
SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE
MINUS
SELECT ENO, ENAME, SAL, DNO
FROM EMPLOYEE 
WHERE DNO NOT IN (20, 30)
OR SAL <=2000;

--Q4
SELECT *
FROM EMPLOYEE
WHERE NOT SAL >= 2000
OR NOT SAL <= 3000;

--Q5
SELECT ENAME, ENO, SAL, DNO
FROM EMPLOYEE
WHERE ENAME LIKE '%E%'
AND SAL NOT BETWEEN 1000 AND 2000
AND DNO=30;

--Q6
SELECT *
FROM EMPLOYEE
WHERE COMM IS NULL
AND JOB IN ('MANAGER', 'CLERK')
AND NOT (ENAME LIKE '_L%'); 

SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM EMPLOYEE;

SELECT * 
FROM EMPLOYEE
WHERE UPPER(ENAME) = UPPER('scott');

SELECT ENAME, LENGTH(ENAME)
FROM EMPLOYEE;

SELECT ENAME, LENGTH(ENAME)
FROM EMPLOYEE
WHERE LENGTH(ENAME) >= 5;

SELECT *
FROM EMPLOYEE
WHERE LENGTH(JOB) >= 6;

SELECT JOB, SUBSTR(JOB, 1, 2), SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5)
FROM EMPLOYEE;

SELECT SUBSTR(ENAME, 3)
FROM EMPLOYEE;

SELECT JOB,
            SUBSTR(JOB, -LENGTH(JOB)),
            SUBSTR(JOB, -LENGTH(JOB), 2),
            SUBSTR(JOB, -3)
FROM EMPLOYEE;

SELECT * 
FROM EMPLOYEE
WHERE INSTR(ENAME, 'S') > 0;

SELECT *
FROM EMPLOYEE
WHERE ENAME LIKE '%S%';

SELECT '010-1234-5677' AS REPLACE_BEFORE,
        REPLACE('010-1234-5678', '-', ' ') AS REPLACE_1,
        REPLACE('010-1234-5678', '-') AS REPLACE_2
FROM DUAL;

SELECT 'ORACLE',
        LPAD('ORACLE', 10, '#') AS LPAD_1,
        RPAD('ORACLE', 10, '$') AS RPAD_1,
        LPAD('ORACLE', 10) AS LPAD_2,
        RPAD('ORACLE', 10) AS RPAD_2
FROM DUAL;

SELECT CONCAT(ENO, ENAME),
       CONCAT(ENO, CONCAT(' : ', ENAME))
    FROM EMPLOYEE
    WHERE ENAME = 'SCOTT';
    
SELECT ENO || ENAME,
       ENO || ' : ' || ENAME
    FROM EMPLOYEE;
    
SELECT '[' || TRIM(' _ _ oRACLE _ _ ') || ']' AS TRIM,
        '[' || TRIM(LEADING FROM ' _ _ oRACLE _ _ ') || ']' AS TRIM_LEADING,
        '[' || TRIM(TRAILING FROM ' _ _ oRACLE _ _ ') || ']' AS TRIM_TRAILING,
        '[' || TRIM(BOTH FROM ' _ _ oRACLE _ _ ') || ']' AS TRIM_BOTH
    FROM DUAL;
    
SELECT '[' || TRIM(' _ORACLE_ ') || ']' AS TRIM,
       '[' || LTRIM(' _ORACLE_ ') || ']' AS LTRIM,
       '[' || RTRIM(' _ORACLE_ ') || ']' AS RTRIM,
       '[' || LTRIM('<_ORACLE_>', '_<') || ']' AS LTRIM_2,
       '[' || RTRIM('<_ORACLE_>', '_>') || ']' AS RTRIM_2
    FROM DUAL;
    
SELECT ROUND(1234.5678) AS ROUND,
        ROUND(1234.5678, 0) AS ROUND_0,
        ROUND(1234.5678, 1) AS ROUND_1,
        ROUND(1234.5678, 2) AS ROUND_2,
        ROUND(1234.5678, -1) AS ROUND_MINUS1,
        ROUND(1234.5678, -2) AS ROUND_MINUS2
FROM DUAL;

SELECT TRUNC(1234.5678) AS TRUNC,
        TRUNC(1234.5678, 0) AS TRUNC_0,
        TRUNC(1234.5678, 1) AS TRUNC_1,
        TRUNC(1234.5678, 2) AS TRUNC_2,
        TRUNC(1234.5678, -1) AS TRUNC_MINUS1
FROM DUAL;

SELECT MOD(15, 6),
        MOD(10, 2),
        MOD(11, 2)
FROM DUAL;

SELECT SYSDATE AS NOW,
        SYSDATE-1 AS YESTERDAY,
        SYSDATE+1 AS TOMORROW
    FROM DUAL;
    
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3)
FROM DUAL;


SELECT *
FROM EMPLOYEE;

SELECT HIREDATE, ADD_MONTHS(TO_DATE(HIREDATE), 120) AS WORK10YEAR
FROM EMPLOYEE;

SELECT ENO, ENAME, HIREDATE, SYSDATE
FROM EMPLOYEE
WHERE ADD_MONTHS(TO_DATE(HIREDATE), 450) > SYSDATE;

SELECT SYSDATE,
    NEXT_DAY(SYSDATE, '화요일'),
    LAST_DAY(SYSDATE)
FROM DUAL;

SELECT ENO, ENAME, ENO+'500'
FROM EMPLOYEE
WHERE ENAME = 'SCOTT';